dataset:
  debug: false
  max_video_len: 256
  max_len: 64
  # split: valid
  # train_for_test: true
  split: test
  meta_processor: BOBSLMetaProcessorV2
  video_processor: SignCLIPPoseProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  test_path: data/<dataset>/test.txt # placeholder, no use
  vfeat_dir: /scratch/shared/beegfs/zifan/bobsl/original_videos
  vfeat_dir_test: /scratch/shared/beegfs/zifan/bobsl/islr_videos
  aligner: DSAligner
  pose_components: 'reduced_face'
  # anonym_pose: true
slurm_config: big
task_type: local_predict
fairseq:
  dataset:
    # batch_size: 256
    batch_size: 512
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri_v1_1/baseline_temporal/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 609
eval:
  save_path: runs/retri_bsl/baseline_temporal_v2/eval
metric: RWTHFSMetric
predictor: RetrievalPredictor
