dataset:
  # debug: true
  max_video_len: 32
  max_len: 32
  split: train
  train_for_test: true
  # split: test
  meta_processor: SignCLIPMetaProcessorV2
  video_processor: SignCLIPPoseProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  data_dir: /scratch/shared/beegfs/zifan/tensorflow_datasets
  test_datasets: [['bobsl_islr', '1.4.0']]
  config_name: holistic_lip
  test_path: data/<dataset>/test.txt # placeholder, no use
  aligner: DSAligner
  pose_components: 'reduced_face'
  include_lip_reading: true
  sp_universal_tagging: true
slurm_config: big
task_type: local_predict
fairseq:
  dataset:
    batch_size: 12800
    # batch_size: 16
    valid_subset: test
    num_workers: 0
  common_eval:
    path: runs/retri_bsl/bobsl_islr_lip/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 1377
eval:
  save_path: runs/retri_bsl/bobsl_islr_lip/eval
metric: RWTHFSMetric
predictor: RetrievalPredictor
