dataset:
  debug: true
  max_video_len: 256
  max_len: 64
  meta_processor: SignCLIPMetaProcessor
  video_processor: SignCLIPPoseProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  data_dir: /shares/iict-sp2.ebling.cl.uzh/common/tensorflow_datasets
  train_datasets: [
    ['sign_suisse', '1.0.0'],
  ]
  valid_datasets: [
    ['sign_suisse', '1.0.0'],
  ]
  test_path: data/<dataset>/test.txt # placeholder, no use
  val_path: data/<dataset>/val.txt # placeholder, no use
  train_path: data/<dataset>/train.txt # placeholder, no use
  aligner: DSAligner
  pose_components: 'reduced_face'
  sp_universal_tagging: true
  pre_compute_vfeat: true
  # preprocess_gloss: true
  # augment_temporal: true
fairseq:
  common:
    fp16: true
    tensorboard_logdir: run
    log_interval: 1000
  dataset:
    num_workers: 2
    batch_size: 448
  optimization:
    lr:
    - 5.0e-05
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000
    warmup_updates: 122
    weight_decay: 0.0
    ddp_backend: no_c10d
    max_epoch: 25
  checkpoint:
    restore_file: runs/retri_v1_1/baseline_temporal/checkpoint_best.pt
    no_epoch_checkpoints: true
    reset_optimizer: true
    reset_dataloader: true
    reset_meters: true
    save_dir: runs/retri_suisse/suisse_finetune
task_type: sweep_small
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 609
loss:
  loss_cls: MMContraLoss
eval:
  save_path: runs/retri_suisse/suisse_finetune
