dataset:
  # debug: true
  max_video_len: 256
  max_len: 64
  split: test
  # split: train
  # train_for_test: true
  meta_processor: SignCLIPSuisseMetaProcessor
  video_processor: SignCLIPPoseProcessor
  text_processor: TextProcessor
  bert_name: bert-base-cased
  test_path: data/signsuisse/metadata_test.csv
  vfeat_dir: /shares/easier.ebling.cl.uzh/WMT_23/signsuisse/mediapipe_new
  vfeat_example_dir: /shares/easier.ebling.cl.uzh/WMT_23/signsuisse/example_mediapipe/
  aligner: DSAligner
  pose_components: 'reduced_face'
  sp_universal_tagging: true
slurm_config: big
task_type: local_predict
fairseq:
  dataset:
    batch_size: 1024
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri_suisse/suisse_finetune/checkpoint_best.pt
model:
  model_cls: MMFusionSeparate
  mm_encoder_cls: null
  video_encoder_cls: MMBertForEncoder
  text_encoder_cls: BertModel
  num_hidden_video_layers: 12
  vfeat_dim: 609
eval:
  save_path: runs/retri_suisse/suisse_finetune/eval
metric: RWTHFSMetric
predictor: RetrievalPredictor
